shoulder_pan_joint:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 0   # Extended Position Control Mode
  Profile_Acceleration: 0
  Profile_Velocity: 0
# shoulder_lift_joint:
#   ID: 2
#   Return_Delay_Time: 0
# elbow_joint:
#   ID: 3
#   Return_Delay_Time: 0
# wrist_1_joint:
#   ID: 4
#   Return_Delay_Time: 0
# wrist_2_joint:
#   ID: 5
#   Return_Delay_Time: 0
# wrist_3_joint:
#   ID: 6
#   Return_Delay_Time: 0
